var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!xxx  ",
   "  x        vv      v                      v                    v      x   v  x  ",
   "  x                 o                                                 x      x  ",
   "  x                                                                   x      x  ",
   "  x                                                                   x      x  ",
   "  x                                                        O         ox      x  ",
   "  x                 y                  y     y                        x      x  ",
   "  x                  y                                              o x    o x  ",
   "  x                              xxxxxiiiiiiiiiiixxxxxxxxxxxxxxxxxxxxxx      x  ",
   "  x              xxx    x      xxxxxx     T      xxxxxxxxxxxxxxxxxxxxxx    xxx  ",
   "  x            xxxxxxxxxxx    xxxxxxx   O        xxxxxxxxxxxxxxxxxxxxxxo   xxx  ",
   "  x   @      xxxxxxxxxxxxxx                        o                     xxxxx  ",
   "  x        xxxxxxxxxxxxxxxxx                                             Zixxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                        o        ",
   "iiii    iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
   "                                           o                                     ",
   "     y                                                                           ",
   "!=                                                                               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxiiiiixxxxxxxxxxxxxxxxx|xxxxxxxxxxx          ",
   "                                                                           x o   ",
   "                                                                         xxxxxxxx",
   "@       o                                                               xxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOxxxxxxxxxxxxxxxxxxxxx",
   "                                       o                                         ",
   "                                                                                 ",
   "@                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxxxxx  ",
   "                                                                                 ",
   "                                                                                 ",
   "iZ                                          O                                    ",
   "xxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                 ",
   "                                                                                 ",
   "o                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxx",
   "                         ",
   "@                       @",
   "y          o            y",
   "xxxxxxxxxx     iiiiiiiiii",
   "        O                ",
   "@                       @",
   "y                       y",
   "iiiiiiiiii     xxxxxxxxxx",
   "                         ",
   "@                o      @",
   "y                       y",
   "xxxxxxxxxx     iiiiiiiiii",
   "                         ",
   "@                       @",
   "y                       y",
   "iiiiiiiiii     xxxxxxxxxx",
   "                         ",
   "                         ",
   "                         ",
   "       i         i       ", 
   "       i         i       ", 
   "       i         i       ", 
   "        i       i        ", 
   "        i       i        ", 
   "  o     i       i        ", 
   "         i     i         ", 
   "         i     i         ", 
   "   y     i     i         ", 
   " O    y   i   i          ", 
   "          x   x          ",
   "    y     x   x          ",
   "           xox           ",
   "      y    x x           ",
   "@          x x           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x                                                          |t|t                                    T       v                               =x  ",
   "  x                                                                                                                                          Zx  ",
   "  x                                                                                                                                          =x  ",
   "  x                                                                                                                                          Zx  ",
   "  x        y     y     y     y     y     y     y     y                                                                                        x  ",
   "  x       y   oo        oo      oooo         oo        oo             OO            OO            OO     OO      OO       OO      OOOOOOOOOO  x  ",
   "  x      y     oo      oo     oo    oo       oo        oo              OO          OOOO          OO      OO      OOO      OO       OOOOOOOO   x  ",
   "  x    yy       oo    oo     oo      oo      oo        oo               OO        OO  OO        OO               OO OO    OO        OOOOOO    x  ",
   "  x              oo  oo     oo        oo     oo        oo                OO      OO    OO      OO        OO      OO  OO   OO         OOOO     x  ",
   "  x y              ooo      oo        oo     oo        oo                 OO    OO      OO    OO         OO      OO   OO  OO          OO      x  ",
   "  x                oo        oo      oo      oo        oo                  OO  OO        OO  OO          OO      OO    OO OO                  x  ",
   "  x    y          oo          oo    oo        oo      oo                    OOOO          OOOO           OO      OO     OOOO          OO      x  ",
   "  x              oo             oooo            oooooo                       OO            OO            OO      OO       OO          OO      x  ",
   "  x y                                                                                                                                         x  ",
   "  x   @       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooox  ",
   "  xxxxxxxxxixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxx  ",
   "                                                                                                                                                 ",
   "                                                                                                                                                 ",
   "                                                                                                                                                 ",
   "                                                                                                                                                 ",
   "                                                                                                                                                 ",
   "                                                                                                                                                 "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
