import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'
// import 'tailwindcss/tailwind.css'
// import grid from '../components/grid'
// import card from '../components/card'
import styles from '../styles/main.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Siarune</title>
        <meta name="styles.Description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <div className="styles.grid">

<div className="styles.card">
    <a href="/projects/games/dino.html" className="link"></a>
        <img src="/img/dino.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/games/dino.html">Dino</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            The classNameic dinosaur game I ripped.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/pages/progress.html" className="link"></a>
        <img src="/img/loading.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="/projects/pages/progress.html">Loading Simulator</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            You gotta be super bored for this.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/games/snake.html" className="link"></a>
        <img src="/img/snake.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/games/snake.html">Snake</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            Snekkkkk
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/games/tetris.html" className="link"></a>
        <img src="/img/tetris.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/games/tetris.html">Tetris</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            Bad janky tetris but still tetris.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/games/jim.html" className="link"></a>
        <img src="/img/jimlsd.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/games/jim.html">Jim</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            You can play it, but you'll hate it as
            much as I do.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/games/russianroulette.html" className="link"></a>
        <img src="/img/nyangun.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/games/russianroulette.html">Russian Roulette</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            Made it at like 4am to play in className.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/games/2048.html" className="link"></a>
        <img src="/img/2048.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/games/2048.html">2048</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            classNameic rage game that I definitely beat.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/games/flappy.html" className="link"></a>
        <img src="/img/flappy.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/games/flappy.html">Flappy Box</a></h3>
        <h5 className="styles.Tag">Game</h5>
        <h4 className="styles.Description">
            Me after the 18th coffee wears off at 5am.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/ascii/elmo.html" className="link"></a>
        <img src="/img/elmo.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/ascii/elmo.html">Elmo</a></h3>
        <h5 className="styles.Tag">ASCII Art</h5>
        <h4 className="styles.Description">
            Applaud your new overlord.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/ascii/squidward.html" className="link"></a>
        <img src="/img/squidward.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/ascii/squidward.html">Squidward</a></h3>
        <h5 className="styles.Tag">ASCII Art</h5>
        <h4 className="styles.Description">
            Our lord and savior.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/ascii/deusvult.html" className="link"></a>
        <img src="/img/deusvult2.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/ascii/deusvult.html">Duesvult</a></h3>
        <h5 className="styles.Tag">ASCII Art</h5>
        <h4 className="styles.Description">
            Chibi knight to the rescue!
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/ascii/derp.html" className="link"></a>
        <img src="/img/derp.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/">Derp</a></h3>
        <h5 className="styles.Tag">ASCII Art</h5>
        <h4 className="styles.Description">
            Derp.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/owo/bible.html" className="link"></a>
        <img src="/img/biblecrack.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/owo/bible.html">Biblowo</a></h3>
        <h5 className="styles.Tag">OwO</h5>
        <h4 className="styles.Description">
            Everybody gangsta til Jesus walks in with a shotgun.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/owo/bee.html" className="link"></a>
        <img src="/img/bee.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/owo/bee.html">Bee</a></h3>
        <h5 className="styles.Tag">OwO</h5>
        <h4 className="styles.Description">
            Yes, the Bee Movie script. No, I was not high.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/owo/shrek.html" className="link"></a>
        <img src="/img/shrek.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/owo/shrek.html">Shrek 2</a></h3>
        <h5 className="styles.Tag">OwO</h5>
        <h4 className="styles.Description">
            You know I had to.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/owo/COMMUNISM.html" className="link"></a>
        <img src="/img/communist.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/owo/COMMUNISM.html">Communism</a></h3>
        <h5 className="styles.Tag">OwO</h5>
        <h4 className="styles.Description">
            The Communist Manifesto for Gen-Z trash.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/owo/Constitution.html" className="link"></a>
        <img src="/img/britain.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/owo/Constitution.html">Constitution</a></h3>
        <h5 className="styles.Tag">OwO</h5>
        <h4 className="styles.Description">
            I pwedge awwegiance to the fwag...
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/pages/annoying.html" className="link"></a>
        <img src="/img/annoying.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/pages/annoying.html">Annoying</a></h3>
        <h5 className="styles.Tag">Something</h5>
        <h4 className="styles.Description">
            I dont even know, this was like my first webpage.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/pages/dictionary.html" className="link"></a>
        <img src="/img/urbandict.jpeg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/pages/dictionary.html">Dictionary</a></h3>
        <h5 className="styles.Tag">Something</h5>
        <h4 className="styles.Description">
            An incomplete dictionary of weird words I found.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/pages/poems.html" className="link"></a>
        <img src="/img/barney.jpg" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/pages/poems.html">Poems</a></h3>
        <h5 className="styles.Tag">Something</h5>
        <h4 className="styles.Description">
            Horrible poetry I made or found.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/pages/nuclear.html" className="link"></a>
        <img src="/img/nuclear.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/pages/nuclear.html">Nuclear</a></h3>
        <h5 className="styles.Tag">Something</h5>
        <h4 className="styles.Description">
            *Severe epilepsy warning*
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/pages/bart.html" className="link"></a>
        <img src="/img/bart.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/pages/bart.html">Bart</a></h3>
        <h5 className="styles.Tag">Something</h5>
        <h4 className="styles.Description">
            My very own discord bot... that hates everything.
        </h4>
</div>

<div className="styles.card">
    <a href="/projects/pages/lotus.html" className="link"></a>
        <img src="/img/lotus.png" className="styles.cover"></img>
        <h3 className="styles.Title"><a href="projects/pages/lotus.html">Lotus</a></h3>
        <h5 className="styles.Tag">Something</h5>
        <h4 className="styles.Description">
            I don't really know but I think it looks nice.
        </h4>
</div>

</div>

      </main>

      <footer classNameName={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span classNameName={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
